name: QQHash
on:
    schedule:
        - cron: "45 11 * * 0"
    workflow_dispatch:
concurrency:
    group: QQHash
    cancel-in-progress: false
jobs:
    qqhash:
        runs-on: ubuntu-latest
        steps:
            - name: 签出
              uses: actions/checkout@v4
              with:
                  path: MoeMoeBots
            - name: 签出 QQHash
              uses: actions/checkout@v4
              with:
                  repository: gui-ying233/QQHash
                  path: QQHash
                  token: ${{ secrets.QQHASH_PAT }}
            - name: 准备 pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: latest
            - name: 准备 node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm
                  cache-dependency-path: MoeMoeBots/pnpm-lock.yaml
            - name: 安装依赖
              run: |
                  sudo apt-get install -y hashcat &
                  cd MoeMoeBots && pnpm install &
                  wait
            - name: 准备 Tailscale
              uses: tailscale/github-action@v4
              with:
                  oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
                  oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
                  tags: tag:ci
                  version: latest
            - name: 运行 QQHash
              env:
                  MOEGIRL_ZH_BOTUSERNAME: ${{ vars.MOEGIRL_ZH_BOTUSERNAME }}
                  MOEGIRL_ZH_BOTPASSWORD: ${{ secrets.MOEGIRL_ZH_BOTPASSWORD }}
                  MOEGIRL_MZH_BOTUSERNAME: ${{ vars.MOEGIRL_MZH_BOTUSERNAME }}
                  MOEGIRL_MZH_BOTPASSWORD: ${{ secrets.MOEGIRL_MZH_BOTPASSWORD }}
                  MOEGIRL_MOEGIRLSSOUSERID: ${{ vars.MOEGIRL_MOEGIRLSSOUSERID }}
                  MOEGIRL_MOEGIRLSSOTOKEN: ${{ secrets.MOEGIRL_MOEGIRLSSOTOKEN }}
                  OTEL_TRACES_EXPORTER: ${{ vars.OTEL_TRACES_EXPORTER }}
                  OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
                  OTEL_EXPORTER_OTLP_INSECURE: ${{ vars.OTEL_EXPORTER_OTLP_INSECURE }}
                  OTEL_NODE_RESOURCE_DETECTORS: ${{ vars.OTEL_NODE_RESOURCE_DETECTORS }}
                  OTEL_SERVICE_NAME: ${{ vars.OTEL_SERVICE_NAME }}
              run: cd MoeMoeBots && node -r ./logger.js QQHash
            - name: 提交 QQHash
              run: |
                  cd QQHash
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add -A
                  git diff --staged --quiet || git commit -m "Update QQHash"
                  git push
