name: QQHash
on:
    schedule:
        - cron: "0 0/12 * * *"
    workflow_dispatch:
concurrency:
    group: QQHash
    cancel-in-progress: false
jobs:
    qqhash:
        runs-on: ubuntu-latest
        steps:
            - name: 签出
              uses: actions/checkout@v4
              with:
                  path: MoeMoeBots
            - name: 签出 QQHash
              uses: actions/checkout@v4
              with:
                  repository: gui-ying233/QQHash
                  path: QQHash
                  token: ${{ secrets.QQHASH_PAT }}
            - name: 设置 node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm
                  cache-dependency-path: MoeMoeBots/package-lock.json
            - name: 安装 npm 依赖
              run: cd MoeMoeBots && npm install
            - name: 运行QQHash
              env:
                  MOEGIRL_ZH_BOTUSERNAME: ${{ vars.MOEGIRL_ZH_BOTUSERNAME }}
                  MOEGIRL_ZH_BOTPASSWORD: ${{ secrets.MOEGIRL_ZH_BOTPASSWORD }}
                  MOEGIRL_MZH_BOTUSERNAME: ${{ vars.MOEGIRL_MZH_BOTUSERNAME }}
                  MOEGIRL_MZH_BOTPASSWORD: ${{ secrets.MOEGIRL_MZH_BOTPASSWORD }}
                  MOEGIRL_MOEGIRLSSOUSERID: ${{ vars.MOEGIRL_MOEGIRLSSOUSERID }}
                  MOEGIRL_MOEGIRLSSOTOKEN: ${{ secrets.MOEGIRL_MOEGIRLSSOTOKEN }}
              run: cd MoeMoeBots && node QQHash
            - name: 提交 QQHash
              run: |
                  cd QQHash
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add -A
                  git diff --staged --quiet || git commit -m "Update QQHash"
                  git push
